package View;
import Model.ModelClientes;
import Controller.ControllerClientes;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class ViewClientes extends javax.swing.JInternalFrame {
    ArrayList<ModelClientes> ListaDeClientes = new ArrayList<>();
    ControllerClientes ControleDeClientes = new ControllerClientes();
    ModelClientes modelClientes = new ModelClientes();
    String SaveOrChange;
    
    public ViewClientes() {
        initComponents();
        MostrarListaDeClientes();
        PainelDetalhesCliente.setVisible(false);
        HabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelBuscaCliente = new javax.swing.JPanel();
        txtPesquisarCliente = new javax.swing.JTextField();
        btnPesquisarCliente = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        listTodosCliente = new javax.swing.JScrollPane();
        TabelaCliente = new javax.swing.JTable();
        btnNovoCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnInfoCliente = new javax.swing.JButton();
        PainelDetalhesCliente = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        txtCPFCliente = new javax.swing.JFormattedTextField();
        lblIdCliente = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        lblContatoFixo = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        lblContatoWtp = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        txtEnderecoCliente = new javax.swing.JTextField();
        lblNumeroCasa = new javax.swing.JLabel();
        txtNumeroCasa = new javax.swing.JTextField();
        btnSalvarCliente = new javax.swing.JButton();
        btnOcultarInfo = new javax.swing.JButton();
        txtTelefoneWtp = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Gerenciamento de Clientes");
        setVisible(true);

        PainelBuscaCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarClienteActionPerformed(evt);
            }
        });
        txtPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarClienteKeyPressed(evt);
            }
        });

        btnPesquisarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.gif"))); // NOI18N
        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        lblInfo.setText("<html>*Nome ou CPF do cliente</html>");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciamento de Clientes");

        TabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "WhatsApp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClienteMouseClicked(evt);
            }
        });
        listTodosCliente.setViewportView(TabelaCliente);
        if (TabelaCliente.getColumnModel().getColumnCount() > 0) {
            TabelaCliente.getColumnModel().getColumn(0).setMinWidth(45);
            TabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(45);
            TabelaCliente.getColumnModel().getColumn(0).setMaxWidth(45);
            TabelaCliente.getColumnModel().getColumn(1).setMinWidth(170);
            TabelaCliente.getColumnModel().getColumn(1).setPreferredWidth(170);
            TabelaCliente.getColumnModel().getColumn(2).setMinWidth(140);
            TabelaCliente.getColumnModel().getColumn(2).setPreferredWidth(140);
            TabelaCliente.getColumnModel().getColumn(2).setMaxWidth(140);
            TabelaCliente.getColumnModel().getColumn(3).setMinWidth(100);
            TabelaCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
            TabelaCliente.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        btnNovoCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.gif"))); // NOI18N
        btnNovoCliente.setText("Novo");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_edit.gif"))); // NOI18N
        btnAlterarCliente.setText("Alterar");
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_remove.gif"))); // NOI18N
        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        btnInfoCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInfoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/theme.gif"))); // NOI18N
        btnInfoCliente.setText("Info");
        btnInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBuscaClienteLayout = new javax.swing.GroupLayout(PainelBuscaCliente);
        PainelBuscaCliente.setLayout(PainelBuscaClienteLayout);
        PainelBuscaClienteLayout.setHorizontalGroup(
            PainelBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelBuscaClienteLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(PainelBuscaClienteLayout.createSequentialGroup()
                        .addGroup(PainelBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listTodosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(PainelBuscaClienteLayout.createSequentialGroup()
                                .addGroup(PainelBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PainelBuscaClienteLayout.createSequentialGroup()
                                        .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisarCliente)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(PainelBuscaClienteLayout.createSequentialGroup()
                                .addComponent(btnNovoCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluirCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInfoCliente)))
                        .addContainerGap())))
        );
        PainelBuscaClienteLayout.setVerticalGroup(
            PainelBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBuscaClienteLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCliente))
                .addGap(0, 0, 0)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listTodosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelBuscaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCliente)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnInfoCliente))
                .addContainerGap())
        );

        PainelDetalhesCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCPF.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblCPF.setText("CPF / CNPJ");

        txtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFClienteActionPerformed(evt);
            }
        });

        lblIdCliente.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblIdCliente.setText("ID Cliente");

        txtIdCliente.setEditable(false);
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblNome.setText("Nome/Razão Social");

        lblEmail.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblEmail.setText("Email");

        txtEmailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailClienteActionPerformed(evt);
            }
        });

        lblContatoFixo.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblContatoFixo.setText("Contato Telefone");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        lblContatoWtp.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblContatoWtp.setText("Contato WhatsApp");

        lblEndereco.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblEndereco.setText("Endereço");

        lblNumeroCasa.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        lblNumeroCasa.setText("Numero");

        txtNumeroCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCasaActionPerformed(evt);
            }
        });

        btnSalvarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/symbol_check.gif"))); // NOI18N
        btnSalvarCliente.setText("Gravar");
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        btnOcultarInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOcultarInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/symbol_no.gif"))); // NOI18N
        btnOcultarInfo.setText("Ocultar");
        btnOcultarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcultarInfoActionPerformed(evt);
            }
        });

        try {
            txtTelefoneWtp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneWtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneWtpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelDetalhesClienteLayout = new javax.swing.GroupLayout(PainelDetalhesCliente);
        PainelDetalhesCliente.setLayout(PainelDetalhesClienteLayout);
        PainelDetalhesClienteLayout.setHorizontalGroup(
            PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                        .addComponent(btnSalvarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOcultarInfo))
                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdCliente)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                        .addComponent(lblCPF)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCPFCliente)))
                            .addComponent(txtNomeCliente)
                            .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(0, 283, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelDetalhesClienteLayout.createSequentialGroup()
                                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEmailCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEnderecoCliente, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18))
                                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContatoFixo)
                                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContatoWtp)
                                            .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                                .addComponent(txtTelefoneWtp, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroCasa)
                                    .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        PainelDetalhesClienteLayout.setVerticalGroup(
            PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF)
                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                        .addComponent(lblIdCliente)
                        .addGap(1, 1, 1)
                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome)
                .addGap(1, 1, 1)
                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                .addComponent(lblEndereco)
                                .addGap(1, 1, 1)
                                .addComponent(txtEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                                .addComponent(lblNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(txtNumeroCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblContatoFixo)
                        .addGap(1, 1, 1)
                        .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefoneWtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelDetalhesClienteLayout.createSequentialGroup()
                        .addComponent(lblContatoWtp)
                        .addGap(21, 21, 21)))
                .addComponent(lblEmail)
                .addGap(1, 1, 1)
                .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(PainelDetalhesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCliente)
                    .addComponent(btnOcultarInfo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelBuscaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(PainelDetalhesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PainelDetalhesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PainelBuscaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Gerenciamento de Cliente - v1.9");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFClienteActionPerformed

    private void txtNumeroCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCasaActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        PesquisarCliente();
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        SaveOrChange = "save";
        PainelDetalhesCliente.setVisible(true);
        LimparCampos();
        HabilitarCampos(true);
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
        if (SaveOrChange.equals("save")) {
            SalvarCliente();
            MostrarListaDeClientes();
        } else if(SaveOrChange.equals("change")){
            AlterarCliente();
            MostrarListaDeClientes();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao gravar Cliente! :(");
        }
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void btnOcultarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcultarInfoActionPerformed
        PainelDetalhesCliente.setVisible(false);
        LimparCampos();
    }//GEN-LAST:event_btnOcultarInfoActionPerformed

    private void txtPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarClienteActionPerformed

    private void txtEmailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        SaveOrChange = "change";
        PainelDetalhesCliente.setVisible(true);
        HabilitarCampos(true);
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoClienteActionPerformed
        PainelDetalhesCliente.setVisible(true);
        HabilitarCampos(false);
        MostrarInfoCliente();
    }//GEN-LAST:event_btnInfoClienteActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        if((JOptionPane.showConfirmDialog(null, 
                "Realmente dejesa excluir o registro?", "Confirmação", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)){
            ExcluirCliente();
        }
        LimparCampos();
        HabilitarCampos(false);
        MostrarListaDeClientes();
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void txtPesquisarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarClienteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            PesquisarCliente();
        }
    }//GEN-LAST:event_txtPesquisarClienteKeyPressed

    private void TabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClienteMouseClicked
        MostrarInfoCliente();
    }//GEN-LAST:event_TabelaClienteMouseClicked

    private void txtTelefoneWtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneWtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneWtpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBuscaCliente;
    private javax.swing.JPanel PainelDetalhesCliente;
    private javax.swing.JTable TabelaCliente;
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnInfoCliente;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnOcultarInfo;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblContatoFixo;
    private javax.swing.JLabel lblContatoWtp;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumeroCasa;
    private javax.swing.JScrollPane listTodosCliente;
    private javax.swing.JFormattedTextField txtCPFCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNumeroCasa;
    private javax.swing.JTextField txtPesquisarCliente;
    private javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JFormattedTextField txtTelefoneWtp;
    // End of variables declaration//GEN-END:variables

    
    //Métodos
    private void SalvarCliente(){
        modelClientes.setNomeCliente(this.txtNomeCliente.getText());
        modelClientes.setCpfCliente(this.txtCPFCliente.getText());
        modelClientes.setEnderecoCliente(this.txtEnderecoCliente.getText());
        modelClientes.setNumCasaCliente(Integer.parseInt(this.txtNumeroCasa.getText()));
        modelClientes.setTelefoneCliente(this.txtTelefone.getText());
        modelClientes.setTelefoneWtpCliente(this.txtCPFCliente.getText());
        modelClientes.setEmailCliente(this.txtEmailCliente.getText());
        if(ControleDeClientes.SalvarClientesController(modelClientes)>0){
            JOptionPane.showMessageDialog(this, "Cliente Cadastrado com Sucesso!");
            LimparCampos();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar dados do cliente! :(");
        }
    }
    
    private void ExcluirCliente(){
        int idCliente = (int) TabelaCliente.getValueAt(TabelaCliente.getSelectedRow(), 0);
        if(ControleDeClientes.ExcluirClientesController(idCliente)){
            JOptionPane.showMessageDialog(this, "Cliente removido com sucesso!");
        }else{
                JOptionPane.showMessageDialog(this, "Erro ao remover cliente! :(");
        }
    }
    
    private void AlterarCliente(){
        modelClientes.setNomeCliente(this.txtNomeCliente.getText());
        modelClientes.setCpfCliente(this.txtCPFCliente.getText());
        modelClientes.setEnderecoCliente(this.txtEnderecoCliente.getText());
        modelClientes.setNumCasaCliente(Integer.parseInt(this.txtNumeroCasa.getText()));
        modelClientes.setTelefoneCliente(this.txtTelefone.getText());
        modelClientes.setTelefoneWtpCliente(this.txtCPFCliente.getText());
        modelClientes.setEmailCliente(this.txtEmailCliente.getText());
        if(ControleDeClientes.AlterarClientesController(modelClientes)){
            JOptionPane.showMessageDialog(this, "Dados do cliente alterados com Sucesso!");
            LimparCampos();
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao alterar os dados do cliente! :(");
        }
    }
    
    private void MostrarInfoCliente(){
        try {
            int pIdCliente = (int) TabelaCliente.getValueAt(TabelaCliente.getSelectedRow(), 0);
            modelClientes = ControleDeClientes.PesquisaClientesController(pIdCliente);
            this.txtIdCliente.setText(String.valueOf(modelClientes.getIdCliente()));
            this.txtNomeCliente.setText(modelClientes.getNomeCliente());
            this.txtCPFCliente.setText(modelClientes.getCpfCliente());
            this.txtEnderecoCliente.setText(modelClientes.getEnderecoCliente());
            this.txtNumeroCasa.setText(String.valueOf(modelClientes.getNumCasaCliente()));
            this.txtTelefone.setText(modelClientes.getTelefoneCliente());
            this.txtCPFCliente.setText(modelClientes.getTelefoneWtpCliente());
            this.txtEmailCliente.setText(modelClientes.getEmailCliente());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Nenhum cliente selecionado!");
        }
    }
        
    private void PesquisarCliente(){
        DefaultTableModel Tabela = (DefaultTableModel) TabelaCliente.getModel();
        final TableRowSorter<DefaultTableModel> Pesquisa = new TableRowSorter<>(Tabela);
        this.TabelaCliente.setRowSorter(Pesquisa);
        String filtro = txtPesquisarCliente.getText();
        Pesquisa.setRowFilter(RowFilter.regexFilter(filtro, 1,2));
    }
    
    //Preenche na lista TODOS os protudos no DB
    private void MostrarListaDeClientes(){
        ListaDeClientes = ControleDeClientes.ListaClientesController();
        DefaultTableModel Tabela = (DefaultTableModel) TabelaCliente.getModel();
        Tabela.setNumRows(0);
        
        for (int i = 0; i < ListaDeClientes.size(); i++) {
            Tabela.insertRow(i, new Object[]{
                ListaDeClientes.get(i).getIdCliente(),
                ListaDeClientes.get(i).getNomeCliente(),
                ListaDeClientes.get(i).getCpfCliente(),
                ListaDeClientes.get(i).getTelefoneWtpCliente()
            });
        }
    }
    
    private void LimparCampos(){
        txtIdCliente.setText("");
        txtNomeCliente.setText("");
        txtCPFCliente.setText("");
        txtEnderecoCliente.setText("");
        txtNumeroCasa.setText("");
        txtTelefone.setValue("");
        txtCPFCliente.setText("");
        txtEmailCliente.setText("");
    }
    
    private void HabilitarCampos(boolean VF){
        txtNomeCliente.setEditable(VF);
        txtCPFCliente.setEditable(VF);
        txtEnderecoCliente.setEditable(VF);
        txtNumeroCasa.setEditable(VF);
        txtTelefone.setEditable(VF);
        txtCPFCliente.setEditable(VF);
        txtEmailCliente.setEditable(VF);
    }
}
