package View;

import java.awt.Dimension;

/**
 *
 * @author Matheus
 */
public class ViewHome extends javax.swing.JFrame {


    public ViewHome() {
        initComponents();
        //Método para deixar a tela em FULLSCREEN
        setExtendedState(MAXIMIZED_BOTH);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AçõesRápidas = new javax.swing.JPanel();
        btnAddClientes = new javax.swing.JButton();
        btnAddProdutos = new javax.swing.JButton();
        btnAddVendas = new javax.swing.JButton();
        btnAddCarrinho = new javax.swing.JButton();
        btnCloseSpeedAction = new javax.swing.JButton();
        Icon = new javax.swing.JLabel();
        PainelAbas = new javax.swing.JTabbedPane();
        Home = new componentes.UJPanelImagem();
        AbaClientes = new javax.swing.JPanel();
        addClientes = new javax.swing.JDesktopPane();
        AbaProdutos = new javax.swing.JPanel();
        addProdutos = new javax.swing.JDesktopPane();
        AbaVendas = new javax.swing.JPanel();
        addVendas = new javax.swing.JDesktopPane();
        AbaCarrinho = new javax.swing.JPanel();
        addCarrinho = new javax.swing.JDesktopPane();
        Menu = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MnSair = new javax.swing.JMenuItem();
        Cadastrar = new javax.swing.JMenu();
        CadastroCliente = new javax.swing.JMenuItem();
        CadastroProduto = new javax.swing.JMenuItem();
        CadastroUsuario = new javax.swing.JMenuItem();
        Opções = new javax.swing.JMenu();
        SpeedActions = new javax.swing.JMenuItem();
        Ajuda = new javax.swing.JMenu();
        Sobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("e-Commerce Management System - v.2.0");

        AçõesRápidas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAddClientes.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnAddClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.gif"))); // NOI18N
        btnAddClientes.setText("Clientes");
        btnAddClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientesActionPerformed(evt);
            }
        });

        btnAddProdutos.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnAddProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/package.gif"))); // NOI18N
        btnAddProdutos.setText("Produtos");
        btnAddProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdutosActionPerformed(evt);
            }
        });

        btnAddVendas.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnAddVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/album.gif"))); // NOI18N
        btnAddVendas.setText("Vendas");
        btnAddVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVendasActionPerformed(evt);
            }
        });

        btnAddCarrinho.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        btnAddCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart.gif"))); // NOI18N
        btnAddCarrinho.setText("Carrinho");
        btnAddCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarrinhoActionPerformed(evt);
            }
        });

        btnCloseSpeedAction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/monitor.gif"))); // NOI18N
        btnCloseSpeedAction.setText("Ações Rápidas");
        btnCloseSpeedAction.setToolTipText(""); // NOI18N
        btnCloseSpeedAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseSpeedActionActionPerformed(evt);
            }
        });

        Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/VancollBlack.png"))); // NOI18N

        javax.swing.GroupLayout AçõesRápidasLayout = new javax.swing.GroupLayout(AçõesRápidas);
        AçõesRápidas.setLayout(AçõesRápidasLayout);
        AçõesRápidasLayout.setHorizontalGroup(
            AçõesRápidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AçõesRápidasLayout.createSequentialGroup()
                .addGroup(AçõesRápidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AçõesRápidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAddClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddCarrinho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddProdutos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCloseSpeedAction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddVendas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AçõesRápidasLayout.setVerticalGroup(
            AçõesRápidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AçõesRápidasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnAddClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Icon)
                .addGap(1, 1, 1)
                .addComponent(btnCloseSpeedAction, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PainelAbas.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        Home.setImagem(new java.io.File("C:\\Users\\Matheus\\Pictures\\#WallpapersHD\\War.jpg"));

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        PainelAbas.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/Imagens/clock.gif")), Home); // NOI18N

        javax.swing.GroupLayout addClientesLayout = new javax.swing.GroupLayout(addClientes);
        addClientes.setLayout(addClientesLayout);
        addClientesLayout.setHorizontalGroup(
            addClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        addClientesLayout.setVerticalGroup(
            addClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AbaClientesLayout = new javax.swing.GroupLayout(AbaClientes);
        AbaClientes.setLayout(AbaClientesLayout);
        AbaClientesLayout.setHorizontalGroup(
            AbaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addClientes)
        );
        AbaClientesLayout.setVerticalGroup(
            AbaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addClientes, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        PainelAbas.addTab("Clientes", new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.gif")), AbaClientes); // NOI18N

        javax.swing.GroupLayout addProdutosLayout = new javax.swing.GroupLayout(addProdutos);
        addProdutos.setLayout(addProdutosLayout);
        addProdutosLayout.setHorizontalGroup(
            addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        addProdutosLayout.setVerticalGroup(
            addProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AbaProdutosLayout = new javax.swing.GroupLayout(AbaProdutos);
        AbaProdutos.setLayout(AbaProdutosLayout);
        AbaProdutosLayout.setHorizontalGroup(
            AbaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(AbaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addProdutos))
        );
        AbaProdutosLayout.setVerticalGroup(
            AbaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(AbaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addProdutos))
        );

        PainelAbas.addTab("Produtos", new javax.swing.ImageIcon(getClass().getResource("/Imagens/package.gif")), AbaProdutos); // NOI18N

        javax.swing.GroupLayout addVendasLayout = new javax.swing.GroupLayout(addVendas);
        addVendas.setLayout(addVendasLayout);
        addVendasLayout.setHorizontalGroup(
            addVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        addVendasLayout.setVerticalGroup(
            addVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AbaVendasLayout = new javax.swing.GroupLayout(AbaVendas);
        AbaVendas.setLayout(AbaVendasLayout);
        AbaVendasLayout.setHorizontalGroup(
            AbaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addVendas)
        );
        AbaVendasLayout.setVerticalGroup(
            AbaVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addVendas)
        );

        PainelAbas.addTab("Vendas", new javax.swing.ImageIcon(getClass().getResource("/Imagens/album.gif")), AbaVendas); // NOI18N

        javax.swing.GroupLayout addCarrinhoLayout = new javax.swing.GroupLayout(addCarrinho);
        addCarrinho.setLayout(addCarrinhoLayout);
        addCarrinhoLayout.setHorizontalGroup(
            addCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        addCarrinhoLayout.setVerticalGroup(
            addCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout AbaCarrinhoLayout = new javax.swing.GroupLayout(AbaCarrinho);
        AbaCarrinho.setLayout(AbaCarrinhoLayout);
        AbaCarrinhoLayout.setHorizontalGroup(
            AbaCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(AbaCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addCarrinho))
        );
        AbaCarrinhoLayout.setVerticalGroup(
            AbaCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(AbaCarrinhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addCarrinho))
        );

        PainelAbas.addTab("Carrinho", new javax.swing.ImageIcon(getClass().getResource("/Imagens/cart.gif")), AbaCarrinho); // NOI18N

        Arquivo.setText("Arquivo");

        jMenuItem1.setText("Exportar");
        Arquivo.add(jMenuItem1);

        jMenuItem2.setText("Imprimir");
        Arquivo.add(jMenuItem2);

        MnSair.setText("Sair");
        MnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairActionPerformed(evt);
            }
        });
        Arquivo.add(MnSair);

        Menu.add(Arquivo);

        Cadastrar.setText("Cadastrar");

        CadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        CadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_add.gif"))); // NOI18N
        CadastroCliente.setText("Cliente");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastroCliente);

        CadastroProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        CadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/package_add.gif"))); // NOI18N
        CadastroProduto.setText("Produtos");
        CadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroProdutoActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastroProduto);

        CadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        CadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/monitor.gif"))); // NOI18N
        CadastroUsuario.setText("Usuário");
        CadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroUsuarioActionPerformed(evt);
            }
        });
        Cadastrar.add(CadastroUsuario);

        Menu.add(Cadastrar);

        Opções.setText("Opções");

        SpeedActions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/monitor.gif"))); // NOI18N
        SpeedActions.setText("Ações Rápidas");
        SpeedActions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedActionsActionPerformed(evt);
            }
        });
        Opções.add(SpeedActions);

        Menu.add(Opções);

        Ajuda.setText("Ajuda");
        Menu.add(Ajuda);

        Sobre.setText("Sobre");
        Menu.add(Sobre);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AçõesRápidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PainelAbas))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelAbas)
            .addComponent(AçõesRápidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //Instanciando os objetos VIEW
    ViewCarrinho addTelaCarrinho = new ViewCarrinho();
    ViewClientes addTelaClientes = new ViewClientes();
    ViewProdutos addTelaProdutos = new ViewProdutos();
    
    private void MnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnSairActionPerformed

    private void SpeedActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedActionsActionPerformed
        AçõesRápidas.setVisible(true);      
    }//GEN-LAST:event_SpeedActionsActionPerformed

    private void btnAddCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarrinhoActionPerformed
        addCarrinho.removeAll();
        Dimension resolucao = addCarrinho.getSize();
        addTelaCarrinho.setSize(resolucao);
        addCarrinho.add(addTelaCarrinho);
        addTelaCarrinho.setLocation(0, 0);
        PainelAbas.setSelectedIndex(4);
        addTelaCarrinho.setVisible(true);
    }//GEN-LAST:event_btnAddCarrinhoActionPerformed

    private void btnAddClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientesActionPerformed
        addClientes.removeAll();
        Dimension resolucao = addClientes.getSize();
        addTelaClientes.setSize(resolucao);
        addClientes.add(addTelaClientes);
        addTelaClientes.setLocation(0, 0);
        PainelAbas.setSelectedIndex(1);
        addTelaClientes.setVisible(true);
    }//GEN-LAST:event_btnAddClientesActionPerformed

    private void btnAddProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdutosActionPerformed
        addProdutos.removeAll();
        Dimension resolucao = addProdutos.getSize();
        addTelaProdutos.setSize(resolucao);
        addProdutos.add(addTelaProdutos);
        addTelaClientes.setLocation(0, 0);
        PainelAbas.setSelectedIndex(2);
        addTelaProdutos.setVisible(true);
    }//GEN-LAST:event_btnAddProdutosActionPerformed

    private void btnCloseSpeedActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseSpeedActionActionPerformed
        //standy by
    }//GEN-LAST:event_btnCloseSpeedActionActionPerformed

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        btnAddClientesActionPerformed(evt);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void CadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroProdutoActionPerformed
        btnAddProdutosActionPerformed(evt);
    }//GEN-LAST:event_CadastroProdutoActionPerformed

    private void CadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroUsuarioActionPerformed
        new ViewUsuarios().setVisible(true);
    }//GEN-LAST:event_CadastroUsuarioActionPerformed

    private void btnAddVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddVendasActionPerformed

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaCarrinho;
    private javax.swing.JPanel AbaClientes;
    private javax.swing.JPanel AbaProdutos;
    private javax.swing.JPanel AbaVendas;
    private javax.swing.JMenu Ajuda;
    private javax.swing.JMenu Arquivo;
    private javax.swing.JPanel AçõesRápidas;
    private javax.swing.JMenu Cadastrar;
    private javax.swing.JMenuItem CadastroCliente;
    private javax.swing.JMenuItem CadastroProduto;
    private javax.swing.JMenuItem CadastroUsuario;
    private componentes.UJPanelImagem Home;
    private javax.swing.JLabel Icon;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem MnSair;
    private javax.swing.JMenu Opções;
    private javax.swing.JTabbedPane PainelAbas;
    private javax.swing.JMenu Sobre;
    private javax.swing.JMenuItem SpeedActions;
    private javax.swing.JDesktopPane addCarrinho;
    private javax.swing.JDesktopPane addClientes;
    private javax.swing.JDesktopPane addProdutos;
    private javax.swing.JDesktopPane addVendas;
    private javax.swing.JButton btnAddCarrinho;
    private javax.swing.JButton btnAddClientes;
    private javax.swing.JButton btnAddProdutos;
    private javax.swing.JButton btnAddVendas;
    private javax.swing.JButton btnCloseSpeedAction;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    
    
    //Métodos

}